"""
Django settings for hrwproject project.

Generated by 'django-admin startproject' using Django 2.1.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8*was9ahy!006wg9++$vi-wcg1n$t=9-q*1@ua#8nd7+i%w87!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hrwapp1.apps.Hrwapp1Config',
    'constance',
    'constance.backends.database',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hrwproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'hrwproject/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrwproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# make sure to separate the databases for app portability
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'hrwproject/default.db'),
    },
    'hrwapp1_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'hrwapp1/hrwapp1.db'),
    },
}
DATABASE_ROUTERS = [
    'hrwproject.dbRouter.HrwprojectDBRouter',
    'hrwapp1.dbRouter.Hrwapp1DBRouter',
]


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATICFILES_DIRS = [                                        # non-standard locations
    os.path.join(BASE_DIR, "hrwproject/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "static_collected")    # URL to where static files are collected
STATIC_URL = "/static/"



# (optional settings) Email backend
# email option 1: configure smtp
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS = True
#EMAIL_PORT = 587
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST_USER =  'dirkdiederen@gmail.com'
#EMAIL_HOST_PASSWORD = 'pleasechange'
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#SERVER_EMAIL = EMAIL_HOST_USER

# emails option 2: forgot password, puts sent emails as files in EMAIL_FILE_PATH
# create a directory in the django project called "emails_sent"
# append to hrwproject/settings.py:
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = os.path.join(BASE_DIR, "emails_sent")      # make sure you create a emails_sent folder


# (optional settings) Constance dynamic website settings - see website admin tab
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True # Use this option in order to skip hash verification
CONSTANCE_DBS = ['default']
CONSTANCE_ADDITIONAL_FIELDS = {
    'select_automatic_sitetree': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (("automatic", "Automatic"), ("sitetree", "Sitetree"))
    }],
}
CONSTANCE_CONFIG = {
    'THE_ANSWER': (42, 'Answer to the Ultimate Question of Life, '
                       'The Universe, and Everything'),
    'SELECT_MENU': ('automatic', 'You can set up your own navigation menu using sitetree in the admin panel.', 'select_automatic_sitetree'),
}
CONSTANCE_CONFIG_FIELDSETS = {
    'Stuff1': (
        'THE_ANSWER',
        'SELECT_MENU',
    ),
}

# Queue
Q_CLUSTER = {
    'name': 'HRWprojectDjangoORM',
    'timeout': 1200,	# Timeout in secs for a task
    'save_limit': 100,	# Store latest 10 results only
    'catch_up': False,	# Ignore un-run scheduled tasks
    'orm': 'default'	# Django database connection
}

CACHES = {
    'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'djangoq-localmem',
    }
}